from typing import Any, Protocol


class BaseRepositoryProtocol(Protocol):
    async def find_one(self, query: dict, *args: Any, **kwargs: Any) -> dict | None: ...
    async def insert_one(self, data: dict) -> None: ...
    async def update_one(self, query: dict, data: dict) -> None: ...
    async def delete_one(self, query: dict) -> None: ...
    async def find_all_paginated(
        self, *args: Any, **kwargs: Any
    ) -> tuple[list, int]: ...
